name: PITM pre release

on:
  push:
    tags:
      - "v*.*.*-alpha*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.7.1"
          cache: true

      - name: Write file
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: public_key.jks
          fileDir: ./android/
          encodedString: ${{ secrets.SIGNINGKEYBASE64 }}

      - run: flutter --version
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - run: flutter build appbundle

      - name: Generate checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          method: sha256
          output: build/app/outputs/apk/release/checksum.txt
          patterns: |
            build/app/outputs/apk/release/*.apk

      - name: Pre release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/*,build/app/outputs/apk/release/*.apk"
          prerelease: true
