name: PITM release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
    
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.7.1'
          cache: true
      - run: flutter --version
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - run: flutter build appbundle
    
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/bundle/release/*.aab,build/app/outputs/apk/release/*.apk'
        